---
- hosts: build

  tasks:
  - include_role:
      name: certgen
    #Change the loop variable so the internal task loops don't conflict; cert_var is another name for "item"
    vars:
      testcert: "{{ cert_var }}"
    loop: "{{ certlist }}"
    #Change the loop variable so the internal task loops don't conflict
    loop_control:
      loop_var: cert_var
