---
- hosts: build

  roles:
  - role: env_bootstrap
    vars:
      terraform_file:
#      - name: disconnected
#        content: "{{ disconnected }}"
      - name: esxi_vsphere
        content: "{{ esxi_vsphere }}"
